title: "Bang Bang Bunny"
email: bangbangbunny69@gmail.com
description: "Party! Out now on Bandcamp."
author: Nic The Geek
url: https://nicthegeek.github.io

# Social Profiles
twitter_username:
github_username:
facebook_username: bangbangbunny69
instagram_username: bang_bang_bunny
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Formspree id
formspree_id: xpzeqgyd

# Recaptcha site key
recaptcha_site_key: 6LdjDFkkAAAAADZO3qcdJ-vX3N2ypH8afh6CO3sw

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
theme: jekyll-theme-clean-blog
